ip: "172.20.0.2"
iface: "eth0"
ipam:
  start: "172.20.0.3"
  end: "172.20.0.254"
janitor:
  poll_interval: 5
  timeout: 120
dns:
  upstream: "8.8.8.8"
services:
  - image: "localhost/spring-service:latest"
    host: "orders-service"
    container_port: 8080
  - image: "localhost/spring-service:latest"
    host: "inventory-service"
    container_port: 8080
